spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: rufan
    password: rufan
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092   # <-- AdminClient √º√ß√ºn  M√úTL∆èQ
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.project.order.kafka.OrderConfirmation
      consumer:
        bootstrap-servers: localhost:29092

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products

#
#### üîπ 1. `bootstrap-servers`
#
#```yaml
#bootstrap-servers: localhost:9092
#```
#
#* Kafka **broker-l…ôrinin √ºnvanƒ±dƒ±r**.
#* Producer mesaj g√∂nd…ôrm…ôk √º√ß√ºn **Kafka cluster**-…ô buradan qo≈üulur.
#* √áox broker varsa, verg√ºll…ô ayrƒ±lƒ±r:
#
#```yaml
#bootstrap-servers: broker1:9092,broker2:9092
#```
#
#---
#
#### üîπ 2. `key-serializer`
#
#```yaml
#key-serializer: org.apache.kafka.common.serialization.StringSerializer
#```
#
#* Kafka mesajƒ± h…ôm **key**, h…ôm d…ô **value** g√∂nd…ôrir.
#* Key, mesajƒ±n hansƒ± **partition**-a d√º≈ü…ôc…ôyini m√º…ôyy…ônl…ô≈üdir…ô bil…ôr.
#* `StringSerializer` ‚Üí key string tipind…ôdirs…ô onu byte-a √ßevirir.
#
#---
#
#### üîπ 3. `value-serializer`
#
#```yaml
#value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#```
#
#* Mesajƒ±n **payload-unun (datanƒ±n) seriyala≈üdƒ±rƒ±lmasƒ±** √º√ß√ºn istifad…ô olunur.
#* `JsonSerializer` Java obyektini JSON formatƒ±na √ßevirir.
#* Bizim misalda `OrderConfirmation` obyektini JSON ≈ü…ôklind…ô broker-…ô g√∂nd…ôrir.
#
#---
#
#### üîπ 4. `properties.spring.json.type.mapping`
#
#```yaml
#spring.json.type.mapping: orderConfirmation:com.project.order.kafka.OrderConfirmation
#```
#
#* **JsonSerializer** √º√ß√ºn …ôlav…ô mapping-dir.
#
#* Producer-…ô deyir ki:
#
#  > `"orderConfirmation"` tipind…ô mesaj g…ôls…ô, onu `com.project.order.kafka.OrderConfirmation` Java obyektin…ô map et.
#
#* Bu, x√ºsusil…ô **konsumer t…ôr…ôfd…ô deserialization** √º√ß√ºn lazƒ±mdƒ±r.
#
#* Misal:
#
#  * Producer g√∂nd…ôrir ‚Üí JSON payload
#  * Consumer oxuyur ‚Üí JSON ‚Üí Java obyektin…ô √ßevrilir (`OrderConfirmation`)
#
#---
#
